# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
 CONFIG_ZMK_DISPLAY=y

# Set deep sleep to 30 minutes
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Make bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# &kscan0 {
# 	# Left -> Right
# 	# P0.31, P0.29, P0.02, P1.15, P1.13, P1.11
# 	col-gpios = <&gpio0 31 GPIO_ACTIVE_HIGH>,
# 				<&gpi0 29 GPIO_ACTIVE_HIGH>,
# 				<&gpi0 02 GPIO_ACTIVE_HIGH>,
# 				<&gpi1 15 GPIO_ACTIVE_HIGH>,
# 				<&gpi1 13 GPIO_ACTIVE_HIGH>,
# 				<&gpi1 11 GPIO_ACTIVE_HIGH>;
# 	# Top -> Bottom
# 	# P0.22, P0.24, P1.00, P0.11
# 	row-gpios = <&gpio0 22 GPIO_ACTIVE_HIGH>,
# 				<&gpi0 24 GPIO_ACTIVE_HIGH>,
# 				<&gpi1 00 GPIO_ACTIVE_HIGH>,
# 				<&gpi0 11 GPIO_ACTIVE_HIGH>;
# };